#cloud-config
autoinstall:
  version: 1
  storage:
    config:
      # MUDANÇA CRÍTICA: Trocado 'match' por serial para 'match' por path.
      # Isso é mais robusto contra problemas de timing na inicialização do disco.
      - type: disk
        match:
          path: /dev/nvme0n1
        id: disk-nvme0
        ptable: gpt
      - type: part
        device: disk-nvme0
        number: 1
        id: part-efi
        size: 1G
        flag: boot
      - type: format
        volume: part-efi
        fstype: fat32
      - type: mount
        volume: part-efi
        path: /boot/efi
      - type: part
        device: disk-nvme0
        number: 2
        id: part-root
        size: -1
      - type: format
        volume: part-root
        fstype: btrfs
      - type: mount
        volume: part-root
        path: /
  locale: pt_BR.UTF-8
  keyboard:
    layout: br
  identity:
    realname: 'Italo Cantalupo Lima'
    hostname: 'cantalupo-Orange-Pi-5'
    username: 'cantalupo'
    password: '$y$j9T$7U8nv8Rcw1iPGpDfXo4VS.$Vw0wlJIpVP6qUohJetOUWT4EA54AfjV7Y8.Z6ACOmm8'
  timezone: America/Recife
  codecs:
    install: true
  drivers:
    install: true
  packages:
    - aria2
    - bmon
    - btop
    - build-essential
    - ca-certificates
    - cmake
    - cpufrequtils
    - curl
    - dialog
    - docker.io
    - f2fs-tools
    - fastfetch
    - flatpak
    - font-manager
    - gdu
    - git
    - glances
    - gparted
    - htop
    - iftop
    - iotop-c
    - iperf3
    - iputils-ping
    - libavif16
    - libfuse2
    - libgstreamer-plugins-bad1.0-0
    - libportaudio2
    - maven
    - mesa-utils
    - mono-runtime
    - net-tools
    - nethogs
    - nfs-common
    - openjdk-25-jdk
    - openjdk-8-jdk
    - pandoc
    - pv
    - python3
    - python3-pip
    - python3-venv
    - ripgrep
    - smartmontools
    - sshfs
    - sshpass
    - telnet
    - tmux
    - tree
    - vnstat
    - vulkan-tools
    - webp
    - whois
    - wl-clipboard
    - xclip
    - xfsprogs
  snaps:
    - name: telegram-desktop
    - name: node
      classic: true
  debconf-selections: |
    iperf3 iperf3/start-daemon boolean false
  updates: all
  shutdown: reboot
  user-data:
    runcmd:
      - [usermod, -aG, docker, cantalupo]
      - [systemctl, restart, docker]
      - [su, -, cantalupo, -c, "flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo"]
      - [su, -, cantalupo, -c, "flatpak install flathub md.obsidian.Obsidian -y"]
      - [sh, -c, "echo 'Cloud-init: Tudo pronto em $(date)' >> /home/cantalupo/setup.log"]
